/*
 * This file is generated by jOOQ.
 */
package spring.boiler.plate.spring_boilerplate.jooq;


import spring.boiler.plate.spring_boilerplate.jooq.tables.Author;
import spring.boiler.plate.spring_boilerplate.jooq.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
